[package]
name = "fdqc-tensors"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#intel-mkl-sys = "0.2"
#blas-src = {version = "0.8",features=["intel-mkl"]}
#lapack-src = { version = "0.8",features=["intel-mkl"]}

[dependencies]
lapack-sys = "0.14"
lapack = "0.19"
blas-sys = "0.7"
blas = "0.22"
num-complex = "0.4"
libc = "0.2"
typenum = "1.14"
rayon = "1.5.1"
itertools = "0.10.3"
#blas-src = { version = "0.8", features=["openblas"] }
#lapack-src = { version = "0.8", features=["openblas"] }
#openblas-src = {version = "0.10", features=["static"]}

[dev-dependencies]
criterion = "0.3"

#[[bench]]
#name = "benchmark"
#harness = false
